// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlaPfSRoWp5vNEeuGkLVFE0DHWm2Mpcq4',
    appId: '1:739071929673:web:1dae8dc33c6db3e4263e98',
    messagingSenderId: '739071929673',
    projectId: 'oziovariasi-2c2d2',
    authDomain: 'oziovariasi-2c2d2.firebaseapp.com',
    storageBucket: 'oziovariasi-2c2d2.appspot.com',
    measurementId: 'G-B42GS4F7H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCsWyKUTkm-5CyOp1-Ptc0qGJwlVAvMb0',
    appId: '1:739071929673:android:1b68fabba041b84d263e98',
    messagingSenderId: '739071929673',
    projectId: 'oziovariasi-2c2d2',
    storageBucket: 'oziovariasi-2c2d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChkEQnnseeVDKdOWB8SNYka9MOgP5ari8',
    appId: '1:739071929673:ios:face8f4b3684ee6d263e98',
    messagingSenderId: '739071929673',
    projectId: 'oziovariasi-2c2d2',
    storageBucket: 'oziovariasi-2c2d2.appspot.com',
    iosBundleId: 'com.example.oziovariasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChkEQnnseeVDKdOWB8SNYka9MOgP5ari8',
    appId: '1:739071929673:ios:face8f4b3684ee6d263e98',
    messagingSenderId: '739071929673',
    projectId: 'oziovariasi-2c2d2',
    storageBucket: 'oziovariasi-2c2d2.appspot.com',
    iosBundleId: 'com.example.oziovariasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlaPfSRoWp5vNEeuGkLVFE0DHWm2Mpcq4',
    appId: '1:739071929673:web:b2741dc7140316b1263e98',
    messagingSenderId: '739071929673',
    projectId: 'oziovariasi-2c2d2',
    authDomain: 'oziovariasi-2c2d2.firebaseapp.com',
    storageBucket: 'oziovariasi-2c2d2.appspot.com',
    measurementId: 'G-YS57BMKW1C',
  );
}
